services:
  nats:
    image: nats:latest
    container_name: nats-server
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
  #browser as a service container
  browserless:
    image: ghcr.io/browserless/chromium:v2.19.0
    container_name: browserless-chrome
    ports:
      - "3000:3000"
    environment:
      - CONCURRENT=10
      - TOKEN=secrettoken123
      - DEBUG=browserless:info,browserless:error
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure?token=secrettoken123"]
      interval: 5s
      timeout: 3s
      retries: 5
  worker:
    build: .
    restart: unless-stopped
    environment:
      - NATS_URL=nats:4222
      - BROWSERLESS_URL=ws://browserless:3000?token=secrettoken123
      - MAX_DELIVERIES=3
    depends_on:
      nats:
        condition: service_started
      browserless:
        condition: service_healthy

volumes:
  nats_data:

